apiVersion: v1
kind: Pod
metadata:
  namespace: yaboring-static
  name: database-pod
  labels:
    app.kubernetes.io/instance: database-pod
spec:
  containers:
  - name: database
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "yaboring"
---
apiVersion: v1
kind: Service
metadata:
  namespace: yaboring-static
  name: database-service
  labels:
    app.kubernetes.io/instance: database-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: database-pod
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006